### ISSUE TITLE
Missing files : adr/cache

### ISSUE THREAD

**Issue by Nekrofage** [vendethiel/ezarena#46]
Salut,

Il manque ces fichiers là : https://github.com/psychobunny/adr-rpg/tree/master/adr/cache

**Comment by vendethiel** [comment]
salut,

en théorie ils devraient être générés la 1ère fois que l'ADR tourne... ce n'est pas le cas?

**Comment by vendethiel** [comment]
les cache_tpls sont les fichiers importants, et eux ont l'air présents.

**Comment by vendethiel** [comment]
Je confirme que les fichiers se régènerent bien chez moi. Peut-être un problème de permissions? (je suis sous windows)

**Comment by Nekrofage** [comment]
Perso, je suis Linux. Je tenterais une autre installation.

**Comment by vendethiel** [comment]
Mh, j'ai un mac à portée de main, je testerai demain pour voir :)

**Comment by vendethiel** [comment]
je confirme que les fichiers sont bien regénérés aussi sur mon mac. Mon cache est en `rwxr-xr-x`

**Comment by vendethiel** [comment]
je vais considérer que tout marche :).
