### ISSUE TITLE
can u help me with install NulAvatar_131

### ISSUE THREAD

**Issue by winzombie** [vendethiel/ezarena#51]
idk how do it whith ezarena xD btw this very nice mod

**Comment by vendethiel** [comment]
Can you explain what's the issue?

Also there's no english translation...

**Comment by winzombie** [comment]
cannot install it cuz need edit includes/usercp_viewprofile.php, but u dont have it, cuz u use another profile mod. 
dont need eng when i have google translate :D

**Comment by winzombie** [comment]
it would be great to install it, so ill can do some thing like midorea

**Comment by vendethiel** [comment]
do you really consider the RPG to be so good that google translate is okay? lol that's a compliment

**Comment by vendethiel** [comment]
to be really honest i kinda expect to port the AD&R part to Icy Phoenix. It's much more featureful, and it's in english. (but the RPG will still be in french)

**Comment by Phosphorus-M** [comment]
Yeah Icy Phoenix it's a good project but ezarena it allows me to install some specific mods that Icy Phoenix it don't allow... Examples? Shop Mod by Zarath

**Comment by vendethiel** [comment]
It's still possible to install those... But you're right it's far more complex...

**Comment by winzombie** [comment]
>do you really consider the RPG to be so good that google translate is okay? lol that's a compliment
i dont need eng cuz ima russian)) and can translate game for my needs) had seanc pack of mods in eng) so dont have problem whith it

**Comment by winzombie** [comment]
dont know what say about icy, dont like when alot of mods what i dont need) by the way, youtube bbcode  dont work xD

**Comment by vendethiel** [comment]
I need to take a decision, however:

A few things against EzArena...

 - EzArena doesn't have an english translation and probably never will
 - I don't really have enough time to maintain the "board" part of EzArena as well as Icy Phoenix.
 - Icy Phoenix's plugins system could be extended on a per-need basis (like shop mod. I have no qualms doing it for you).

A few things pro EzArena:

 - Icy Phoenix uses a different layout. It means I'll need to convert the ADR template files and it'll take some time
 - Icy Phoenix isn't compatible with the templates I converted for EzArena :(.

**Comment by winzombie** [comment]
yeap u right, u doing its not for me. ezarena is very good premod. and i say thank u for it=)

**Comment by vendethiel** [comment]
> dont know what say about icy, dont like when alot of mods what i dont need) by the way, youtube bbcode dont work xD

Oh, right, I forgot to pull @Phosphorus-M 's patch for that. Will do later.

> dont know what say about icy, dont like when alot of mods what i dont need)

Have you tried it? If you don't install the plugins for the features you don't need (album etc) they shouldn't be an issue to you.

**Comment by winzombie** [comment]
yeap i tried it, but far far ago. need try again=) thx for advice

**Comment by vendethiel** [comment]
Pulled in @Phosphorus-M 's fix! thanks.

**Comment by vendethiel** [comment]
> yeap i tried it, but far far ago. need try again=) thx for advice

Tell me what you think about it. I think it'd be the best solution for everyone if we can agree.

Also I need to post my "todo list"

**Comment by winzombie** [comment]
> Also I need to post my "todo list"
greet idea

**Comment by vendethiel** [comment]
Here, ^ that's the basic todo list. I have another one more complete, but it's not clean (I have some phpBB-focused mods I don't actually want to add, because the forum has enough features...).
