### ISSUE TITLE
adr_character_list.php

### ISSUE THREAD

**Issue by winzombie** [vendethiel/ezarena#55]
Could not query users

DEBUGGAGE

Ошибка SQL: 1054 Unknown column 'c.character_area' in 'on clause'

Запрос SQL:
SELECT c.* , s.shop_id , s.shop_name , r.race_img , z.zone_name , u.username , u.user_id , u.user_avatar_type , u.user_allowavatar , u.user_avatar FROM phpbb_adr_characters c , phpbb_users u LEFT JOIN phpbb_adr_shops s ON ( s.shop_owner_id = u.user_id ) LEFT JOIN phpbb_adr_zones z ON ( z.zone_id = c.character_area ) LEFT JOIN phpbb_adr_races r ON ( r.race_id = c.character_race ) WHERE c.character_id = u.user_id AND u.user_id > 1 ORDER BY u.username ASC LIMIT 0, 50

Линия: 152
Файл: adr_character_list.php

Ошибка в коде:
Line-146:  
Линия-147:  
Линия-148:  
Линия-149:  
Линия-150:  
Линия-151:  
Линия-152!  
Линия-153:  
Линия-154:  
Линия-155:  
Линия-156:

**Comment by winzombie** [comment]
fixed 
change line 143 from 	FROM " . ADR_CHARACTERS_TABLE . " c  , " . USERS_TABLE . " u  to 	FROM " . ADR_CHARACTERS_TABLE . " c JOIN " . USERS_TABLE . " u

**Comment by vendethiel** [comment]
Needs a "ON", but yeah.
