### ISSUE TITLE
adr_clans is too strict

### ISSUE THREAD

**Issue by vendethiel** [vendethiel/ezarena#56]
only ask for name + desc

**Comment by winzombie** [comment]
thing Renlok  guild mod is better and have more capabilities

**Comment by vendethiel** [comment]
link?

**Comment by vendethiel** [comment]
I used to have Seteo-Bloke's Guild 0.0.3, but it wasn't better than the current mod.

**Comment by vendethiel** [comment]
also UGH this one had SQL injections

**Comment by winzombie** [comment]
https://mega.nz/#!5poBSZwS idk, clan or guil must have more capabilities IMHO

**Comment by vendethiel** [comment]
"Need decryption key"

**Comment by vendethiel** [comment]
> Update: Beta version makes forum invisible to non-guild members

I purposedly didn't include that, because I don't want to tie the forums and RPG together.

**Comment by winzombie** [comment]
!CwVjBxBd_1lu2TjT3f2TEOSoSdgURwsvM-g_lqLiW8I oh sr, dot use mega usualy . btw now clan mod dont load memberlis links, only .../adr_character.php?, and button "invite" from party dissapire

**Comment by vendethiel** [comment]
will try later

**Comment by vendethiel** [comment]
it's true the guilds mod look better than the clans mod, but I already hopped off once...

**Comment by vendethiel** [comment]
the clans' mod "membership" system works with a shitty string system...

**Comment by vendethiel** [comment]
so, okay. I'll probably go for Renlok's guild system. My preferences seem to be:
S-T's Guild Alliances < Nuladion's Clans Mod < Renlok's guilds.

I'm however not installing guild HQ or name/rank in topics until we decided whether to use Ultimarena or Icy Phoenix.

**Comment by vendethiel** [comment]
Starting to remove clans_mod.
