### ISSUE TITLE
pvp troubles

### ISSUE THREAD

**Issue by winzombie** [vendethiel/ezarena#58]
pvp doesn't work correctly, dont show actions

**Comment by vendethiel** [comment]
Currently busy doing other things :). I'm not sure I'll find time before next week.

**Comment by vendethiel** [comment]
Okay. Looking at it now!

**Comment by vendethiel** [comment]
That's very broken indeed.

**Comment by vendethiel** [comment]
I'm tired at this code duplication, ugh. I'm not sure how I can make it better right now.

**Comment by vendethiel** [comment]
To give you an idea:

adr_battle is ~3k lines (external files included)
adr_battle_pvp is ~1.5k lines (external files included)

I'll be looking at ways to share code between those. But I don't want to lie – it's gonna take a looooot of time to rewrite 4k+ lines of tangled code.

**Comment by vendethiel** [comment]
Okay, I fixed spells in PvP. I think this will be done by september, maybe october.

Maybe less time, but I don't want to break promises.

**Comment by vendethiel** [comment]
I fixed pvp.

It's not pretty but should work.
Also added ajax refresh.
