### ISSUE TITLE
remove clans_mod, add guilds by renlok

### ISSUE THREAD

**Issue by vendethiel** [vendethiel/ezarena#59]
Almost done.

I need to integrate the party mod.

https://github.com/vendethiel/ezarena/blob/d8e0e2532a65e9dab73c27e5d873fcb46d9b2a4d/adr_clans.php#L434-L437
- [ ] TODO add the temple thingie
- [ ] TODO make the forum cost configurable (currently hardcoded to 300k at times, 100k at other times)

**Comment by vendethiel** [comment]
It seems Renlok's guild mod is just a small extension to Guild Alliances... Whatever. It's installed...

**Comment by vendethiel** [comment]
- [ ] Add the temple heal % by guilds

**Comment by vendethiel** [comment]
@winzombie are you sure the version you sent me is the correct one? I've had to patch it left and right.

**Comment by winzombie** [comment]
@Phosphorus-M idk, long time ago i install it and it working correctly. thet last version i have. u can look at [https://sourceforge.net/projects/advanceddungeon/files/phpBB2/ADR%20Addons/](url)

**Comment by winzombie** [comment]
another mods pack  little bigger vs sort https://mega.nz/#!g84zyIiA                     !-kAzeJHMCqeckHh_6dvvwu_OFsfOnV0mP-jl6m2Crso

**Comment by vendethiel** [comment]
Some keys are missing and al. i'll try later with a different version. But the installation file is wrong

**Comment by vendethiel** [comment]
> another mods pack little bigger vs sort https://mega.nz/#!g84zyIiA !-kAzeJHMCqeckHh_6dvvwu_OFsfOnV0mP-jl6m2Crso

There's nothing more there...

**Comment by vendethiel** [comment]
Whatever. I'll do whatever I need to...

**Comment by winzombie** [comment]
![2](https://cloud.githubusercontent.com/assets/10268622/18510351/22a1e856-7a86-11e6-8325-252b2db98589.JPG)
![1](https://cloud.githubusercontent.com/assets/10268622/18510352/22a748c8-7a86-11e6-8656-035b7f2e3cf6.JPG)
its working in cgb premod. ill try install  it later too

**Comment by vendethiel** [comment]
Well for example there's nothing in the install.txt that tells you where to put the constants. I can "guess" where they're supposed to be, but that's suboptimal.

**Comment by vendethiel** [comment]
I don't have CGB's premod btw. Does it have interesting mods we don't?

**Comment by winzombie** [comment]
https://sourceforge.net/projects/cgbrpg/ its just another premod, withs few mods and fine prosilverse template

**Comment by vendethiel** [comment]
Okay. I'll download it. Maybe I can extract a few files.

**Comment by vendethiel** [comment]
Note that EzArena's AD&R is a bit too customized to just add in mod like taht.

**Comment by vendethiel** [comment]
Fixing bugs left and right. Still some CSS issues to fix...

**Comment by vendethiel** [comment]
it also does some really really shitty things like DELETING USERGROUPS WHEN THE USER DISBANDS A GUILD

**Comment by vendethiel** [comment]
also there's no security at all. you can delete anyone's guild. What is this shit mod.

**Comment by winzombie** [comment]
this mods writed along ago buy users who know php on school level etc xD what do u want from it)))) btw i very like mods by lagunacid dnd reborn, but i can't install it never=(

**Comment by vendethiel** [comment]
The one that adds D&D rules to AD&R? I think it changes the gameplay a bit too much.

**Comment by winzombie** [comment]
yeap, but imho thats better fighting formula from standart adr.

**Comment by vendethiel** [comment]
idk. maybe as an option. But it's too much work to integrate it only as an option..

**Comment by winzombie** [comment]
yeap. its to strong for my knowledge but. seems to be good
- Infinitely more item attribute customization. You will be able to add item attributes at your ACP. Basic PHP knowledge required. I will be of course give out pre-made item attributes, and other users might want to give out some as well. To "install" 3rd-party attributes, it will be simply an execution of an SQL query.
##	- D&D battle system. Your attack chance will be set as (D20 + Attack Bonus + Bonus from Dexterity) > (Enemy Armor Class). Your damage will be set as D[ITEM POWER] + [ITEM ADD POWER] + Bonus from Might/Intelligence. Weapons use Might, Spells use Intelligence. Wisdom will increment your magical defence and potion effect. Dexterity will improve both attack chance and defence chance. Might will improve weapon damage and attack chance. Constitution will improve HP growth. 
##	- More monster customization. Monsters can use weapons and spells from shops.
================================================================

**Comment by vendethiel** [comment]
There are a lot of mods already installed. They'd all need to be adapted.

**Comment by vendethiel** [comment]
The guild mod is really buggy and really bad. i.e. it uses the character_name as leader...

**Comment by vendethiel** [comment]
Got a lot done. Still got a lot of fixes to do however.

**Comment by vendethiel** [comment]
Okay. I understand now. The `adr_guilds` in cgphpbb is NOT the extended version. It's a basic one with no ranks and al.

**Comment by vendethiel** [comment]
By that, I meant that the one installed is NOT renlok's

**Comment by vendethiel** [comment]
I'm basically rewriting the mod right now, because renlok just can't code.

**Comment by vendethiel** [comment]
Done rewriting `adr_guilds.php`. I'll try to do the `adr_guilds_leaders.php` one soon-ish(™)

**Comment by vendethiel** [comment]
- [ ] TODO add the temple thingie

**Comment by winzombie** [comment]
new trouble in leader control panel:
```
ould not query count for total awaiting approval

DEBUGGAGE

Ошибка SQL: 1054 Unknown column 'character_guild_approval' in 'field list'

Запрос SQL:
SELECT character_guild_approval FROM phpbb_adr_characters WHERE character_guild_approval = 1

Линия: 216
Файл: D:\drou\EasyPHP\www\adr_guilds_leader.php

Ошибка в коде:
Линия-210:   
Линия-211:  	// Count characters awaiting approval 
Линия-212:  	$sql = " SELECT character_guild_approval FROM " . ADR_CHARACTERS_TABLE . " 
Линия-213:  	WHERE character_guild_approval = $guild_id "; 
Линия-214:  	if( !($result = $db->sql_query($sql)) ) 
Линия-215:  	{ 
Линия-216!  	message_die(GENERAL_ERROR, 'Could not query count for total awaiting approval', '', __LINE__, __FILE__, $sql); 
Линия-217:  	} 
Линия-218:  	$total_awaiting = $db->sql_numrows($result); 
Линия-219:   
Линия-220:  	$template->assign_vars(array( 
```

**Comment by vendethiel** [comment]
> vendethiel commented 4 days ago
> Done rewriting adr_guilds.php. I'll try to do the adr_guilds_leaders.php one soon-ish(™)

**Comment by winzombie** [comment]
oh sry dotn see that

**Comment by vendethiel** [comment]
I'm done. Just let me commit and it should be okay™.

I'll still test a few more things out.

You need to try out adding/removing members. I only tested with one character.

**Comment by vendethiel** [comment]
Here. Should be all-good. As you can see, I pretty much rewrote the mods.

The two tiny things to do are listed in the first message of this issue. (I didn't try the forum thing. Not sure I even like it..)

**Comment by vendethiel** [comment]
@winzombie mind confirming if it works (or not)?

**Comment by winzombie** [comment]
oh, try it tomorrow, cuz working

**Comment by vendethiel** [comment]
I'm gonna leave it at that, because it should work correctly.
