### ISSUE TITLE
add quest mod addons

### ISSUE THREAD

**Issue by vendethiel** [vendethiel/ezarena#61]
from @winzombie's pack

**Comment by vendethiel** [comment]
@Nekrofage Je me permets de t'invoquer. Je crois que tu avais une liste de mod que tu avais / voulais installer (House Mod, etc...). Sur ton fork (FJR), tu as un quest mod différent. Est-il meilleur que celui d'Himmelweiss ? Quels autres mods recommandes-tu ?

**Comment by Nekrofage** [comment]
Salut !!! :D 
Pour "quest mod/map", j'avais récupéré la version 2.5.0 (je crois) et j'ai du modifier le code, du genre avoir une carte plus grande et fixer qqch au niveau des sessions.
Je ne connais pas du tout Himmelweiss, tu as un lien ?
J'avais aussi modifier un éditeur/générateur de carte : 
https://github.com/Nekrofage/FJR/tree/develop/fjr/quest 
Duel Card : C'est pas mal 
House : Du peu que je me rappel c'est galère pour installer, à tester de ton côté par curiosité.
"Ma" version moddé du phpbb, c'est quand même du bricolage... O_o

**Comment by vendethiel** [comment]
La version quest d'Himmelweiss est celle installée : faut que tu ailles dans l'interface des PNJs

**Comment by vendethiel** [comment]
Je me permets de fermer ça, sauf si ça t'intéresse d'en rediscuter.

**Comment by Nekrofage** [comment]
Heu, en fait, je sais pas trop... :D

**Comment by vendethiel** [comment]
Haha, j'avoue que j'avais un peu regardé ce que tu faisais avec FJR, mais tu avais arrêté il y a quelques mois il me semble
